In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Navigate to the root directory of your Google Drive
%cd /content/drive/MyDrive/

# Open and display the scatter_matrix.png file
from PIL import Image
im = Image.open('/content/drive/MyDrive/scatter_matrix_D.png')
im.show()

In [ ]:
filepath = '/content/drive/My Drive/input_MD.csv'
dfMD = pd.read_csv(filepath)
dfMD.head()

,Name,class1,class2,class3,class4,BOD,DO,COD,T-N,T-P,...,C10 H10 N4 O2 S,C10 H10 N4 O3 S,C10 H10 O(1/2),C10 H10 O(2/2),C10 H10 O2(1/2),C10 H10 O2(2/2),C10 H10 O3(1/3),C10 H10 O3(2/3),C10 H10 O3(3/3),C10 H10 O3 Se
0,M1(3),M1,M,Mar,M_Mar,1.0,12.8,2.8,2.278,0.013,...,5689578,288450,256711513,14592819,1884331,32856335,1976858,18216733,3574214,22624318
1,M1(4),M1,M,Apr,M_Apr,1.2,11.3,3.2,2.342,0.006,...,12703384,557396,107853229,46474202,3039597,79946000,7932467,730957,802138,37727511
2,M1(5),M1,M,May,M_May,1.2,10.7,3.2,1.326,0.004,...,6865030,3782295,32999591,83662594,8359572,142478492,25025188,4658382,27815401,3634296
3,M1(6),M1,M,Jun,M_Jun,1.2,9.7,3.1,1.670,0.008,...,7302403,508963,37978047,666504990,19180762,226922672,3449662,52297065,8204286,18104129
4,M1(7),M1,M,Jul,M_Jul,1.2,9.3,3.3,1.926,0.014,...,189180232,671240,8259448,12281261,1152124,32485734,4251229,5637563,1359357,197916487

In [ ]:
dfMD_input=dfMD.iloc[:,13:].to_numpy()
dfMD_target=dfMD['class2'].to_numpy()

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(dfMD_input, dfMD_target, random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)
print("Train Accuracy:", lr.score(train_input, train_target))
print("Test Accuracy:", lr.score(test_input, test_target))

1.0
0.6296296296296297

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# 4. MinMax transformation
scaler = MinMaxScaler()
dfMD[dfMD.columns[13:]] = scaler.fit_transform(dfMD[dfMD.columns[13:]])

# Save the transformed data to a new .csv file
dfMD.to_csv("dfMD_MM.csv", index=False)

dfMD_MM = pd.read_csv("dfMD_MM.csv")
dfMD_MM.head()

,Name,class1,class2,class3,class4,BOD,DO,COD,T-N,T-P,...,C10 H10 N4 O2 S,C10 H10 N4 O3 S,C10 H10 O(1/2),C10 H10 O(2/2),C10 H10 O2(1/2),C10 H10 O2(2/2),C10 H10 O3(1/3),C10 H10 O3(2/3),C10 H10 O3(3/3),C10 H10 O3 Se
0,M1(3),M1,M,Mar,M_Mar,1.0,12.8,2.8,2.278,0.013,...,0.003366,0.020053,0.856459,0.017729,0.087624,0.053620,0.040361,0.340246,0.106838,0.057288
1,M1(4),M1,M,Apr,M_Apr,1.2,11.3,3.2,2.342,0.006,...,0.014509,0.082919,0.355120,0.065766,0.148563,0.204787,0.243725,0.001743,0.018081,0.096780
2,M1(5),M1,M,May,M_May,1.2,10.7,3.2,1.326,0.004,...,0.005233,0.836746,0.103021,0.121800,0.429189,0.405527,0.827384,0.077773,0.882999,0.007633
3,M1(6),M1,M,Jun,M_Jun,1.2,9.7,3.1,1.670,0.008,...,0.005928,0.071598,0.119788,1.000000,1.000000,0.676608,0.090652,1.000000,0.255085,0.045469
4,M1(7),M1,M,Jul,M_Jul,1.2,9.3,3.3,1.926,0.014,...,0.294885,0.109531,0.019699,0.014246,0.049000,0.052431,0.118023,0.096729,0.035922,0.515644

In [ ]:
dfMD_MM_input=dfMD_MM.iloc[:,13:].to_numpy()
dfMD_MM_target=dfMD_MM['class2'].to_numpy()

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(dfMD_MM_input, dfMD_MM_target, random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)
print("Train Accuracy:", lr.score(train_input, train_target))
print("Test Accuracy:", lr.score(test_input, test_target))

1.0
0.7407407407407407

In [ ]:
from sklearn.preprocessing import StandardScaler

# 4. Standard transformation
scaler = StandardScaler()
dfMD[dfMD.columns[13:]] = scaler.fit_transform(dfMD[dfMD.columns[13:]])

# Save the transformed data to a new .csv file
dfMD.to_csv("dfMD_ST.csv", index=False)

dfMD_ST = pd.read_csv("dfMD_ST.csv")
dfMD_ST.head()

,Name,class1,class2,class3,class4,BOD,DO,COD,T-N,T-P,...,C10 H10 N4 O2 S,C10 H10 N4 O3 S,C10 H10 O(1/2),C10 H10 O(2/2),C10 H10 O2(1/2),C10 H10 O2(2/2),C10 H10 O3(1/3),C10 H10 O3(2/3),C10 H10 O3(3/3),C10 H10 O3 Se
0,M1(3),M1,M,Mar,M_Mar,1.0,12.8,2.8,2.278,0.013,...,-0.717776,-0.670973,2.940400,-0.229982,-0.307505,-0.598013,-0.511334,2.142616,-0.138932,-0.307733
1,M1(4),M1,M,Apr,M_Apr,1.2,11.3,3.2,2.342,0.006,...,-0.654201,-0.276563,0.901981,0.393563,0.001810,0.068775,0.310721,-0.731926,-0.495977,-0.125564
2,M1(5),M1,M,May,M_May,1.2,10.7,3.2,1.326,0.004,...,-0.707121,4.452752,-0.123041,1.120903,1.426198,0.954233,2.670035,-0.086284,2.983349,-0.536785
3,M1(6),M1,M,Jun,M_Jun,1.2,9.7,3.1,1.670,0.008,...,-0.703157,-0.347590,-0.054867,12.520291,4.323499,2.149960,-0.308042,7.745190,0.457424,-0.362254
4,M1(7),M1,M,Jul,M_Jul,1.2,9.3,3.3,1.926,0.014,...,0.945434,-0.109611,-0.461824,-0.275192,-0.503548,-0.603261,-0.197401,0.074686,-0.424207,1.806583

In [ ]:
dfMD_ST_input=dfMD_ST.iloc[:,13:].to_numpy()
dfMD_ST_target=dfMD_ST['class2'].to_numpy()

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(dfMD_ST_input, dfMD_ST_target, random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)
print("Train Accuracy:", lr.score(train_input, train_target))
print("Test Accuracy:", lr.score(test_input, test_target))

1.0
0.7407407407407407

In [ ]:
from sklearn.preprocessing import RobustScaler

# 4. Robust transformation
scaler = RobustScaler()
dfMD[dfMD.columns[13:]] = scaler.fit_transform(dfMD[dfMD.columns[13:]])

# Save the transformed data to a new .csv file
dfMD.to_csv("dfMD_RB.csv", index=False)

dfMD_RB = pd.read_csv("dfMD_RB.csv")
dfMD_RB.head()

,Name,class1,class2,class3,class4,BOD,DO,COD,T-N,T-P,...,C10 H10 N4 O2 S,C10 H10 N4 O3 S,C10 H10 O(1/2),C10 H10 O(2/2),C10 H10 O2(1/2),C10 H10 O2(2/2),C10 H10 O3(1/3),C10 H10 O3(2/3),C10 H10 O3(3/3),C10 H10 O3 Se
0,M1(3),M1,M,Mar,M_Mar,1.0,12.8,2.8,2.278,0.013,...,-0.236236,-0.441241,6.287144,-0.049647,0.054115,-0.281422,-0.314053,2.732150,0.552288,0.221885
1,M1(4),M1,M,Apr,M_Apr,1.2,11.3,3.2,2.342,0.006,...,-0.176539,0.080770,2.508935,1.260332,1.148143,0.453279,0.914496,-0.137899,-0.320314,0.466930
2,M1(5),M1,M,May,M_May,1.2,10.7,3.2,1.326,0.004,...,-0.226232,6.340133,0.609056,2.788372,6.186119,1.428922,4.440456,0.506734,8.183003,-0.086223
3,M1(6),M1,M,Jun,M_Jun,1.2,9.7,3.1,1.670,0.008,...,-0.222509,-0.013236,0.735416,26.736877,16.433703,2.746435,-0.010237,8.325966,2.009756,0.148546
4,M1(7),M1,M,Jul,M_Jul,1.2,9.3,3.3,1.926,0.014,...,1.325520,0.301735,-0.018879,-0.144627,-0.639279,-0.287205,0.155114,0.667453,-0.144911,3.065954

In [ ]:
dfMD_RB_input=dfMD_RB.iloc[:,13:].to_numpy()
dfMD_RB_target=dfMD_RB['class2'].to_numpy()

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(dfMD_RB_input, dfMD_RB_target, random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)
print("Train Accuracy:", lr.score(train_input, train_target))
print("Test Accuracy:", lr.score(test_input, test_target))

1.0
0.7592592592592593

In [ ]:
# Subtract the mean of each column and divide by the square of the standard deviation of each column
dfMD.iloc[:, 13:] = (dfMD.iloc[:, 13:] - dfMD.iloc[:, 13:].mean()) / dfMD.iloc[:, 13:].std()**0.5

# Move the first column (sample name) and second column (group name) to the front and combine the data
cols = dfMD.columns.tolist()
cols = cols[:13] + cols[13:]
dfMD = dfMD[cols]
dfMD.to_csv("dfMD_PR.csv", index=False)
dfMD_PR = pd.read_csv("dfMD_PR.csv")
dfMD_PR.head()

,Name,class1,class2,class3,class4,BOD,DO,COD,T-N,T-P,...,C10 H10 N4 O2 S,C10 H10 N4 O3 S,C10 H10 O(1/2),C10 H10 O(2/2),C10 H10 O2(1/2),C10 H10 O2(2/2),C10 H10 O3(1/3),C10 H10 O3(2/3),C10 H10 O3(3/3),C10 H10 O3 Se
0,M1(3),M1,M,Mar,M_Mar,1.0,12.8,2.8,2.278,0.013,...,-7.251575,-3.589465,28.213139,-2.110509,-2.034686,-5.713970,-3.675510,15.068461,-1.007332,-2.999913
1,M1(4),M1,M,Apr,M_Apr,1.2,11.3,3.2,2.342,0.006,...,-6.609286,-1.479516,8.654513,3.611668,0.011975,0.657141,2.233489,-5.147448,-3.596102,-1.224047
2,M1(5),M1,M,May,M_May,1.2,10.7,3.2,1.326,0.004,...,-7.143933,23.820630,-1.180575,10.286365,9.436803,9.117625,19.192437,-0.606816,21.630885,-5.232801
3,M1(6),M1,M,Jun,M_Jun,1.2,9.7,3.1,1.670,0.008,...,-7.103880,-1.859485,-0.526451,114.896863,28.607543,20.542705,-2.214232,54.469907,3.316572,-3.531407
4,M1(7),M1,M,Jul,M_Jul,1.2,9.3,3.3,1.926,0.014,...,9.551568,-0.586381,-4.431205,-2.525395,-3.331858,-5.764111,-1.418939,0.525249,-3.075730,17.611322

In [ ]:
dfMD_PR_input=dfMD_PR.iloc[:,13:].to_numpy()
dfMD_PR_target=dfMD_PR['class2'].to_numpy()

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(dfMD_PR_input, dfMD_PR_target, random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)
print("Train Accuracy:", lr.score(train_input, train_target))
print("Test Accuracy:", lr.score(test_input, test_target))

1.0
0.7777777777777778

In [ ]:
filepath = '/content/drive/My Drive/input_MD.csv'
dfMD = pd.read_csv(filepath)
# Log transform the data
dfMD[dfMD.columns[13:]] = np.log(dfMD[dfMD.columns[13:]])
    
# Save the transformed data to a new .csv file
dfMD.to_csv("dfMD_log.csv", index=False)

dfMD_log = pd.read_csv("dfMD_log.csv")
dfMD_log.head()

,Name,class1,class2,class3,class4,BOD,DO,COD,T-N,T-P,...,C10 H10 N4 O2 S,C10 H10 N4 O3 S,C10 H10 O(1/2),C10 H10 O(2/2),C10 H10 O2(1/2),C10 H10 O2(2/2),C10 H10 O3(1/3),C10 H10 O3(2/3),C10 H10 O3(3/3),C10 H10 O3 Se
0,M1(3),M1,M,Mar,M_Mar,1.0,12.8,2.8,2.278,0.013,...,15.554147,12.572277,19.363463,16.496040,14.449083,17.307655,14.497019,16.717851,15.089256,16.934536
1,M1(4),M1,M,Apr,M_Apr,1.2,11.3,3.2,2.342,0.006,...,16.357379,13.231031,18.496282,17.654408,14.927235,18.196862,15.886475,13.502110,13.595036,17.445900
2,M1(5),M1,M,May,M_May,1.2,10.7,3.2,1.326,0.004,...,15.741951,15.145842,17.312006,18.242303,15.938918,18.774702,17.035393,15.354179,17.141100,15.105926
3,M1(6),M1,M,Jun,M_Jun,1.2,9.7,3.1,1.670,0.008,...,15.803714,13.140131,17.452519,20.317558,16.769418,19.240120,15.053787,17.772451,15.920167,16.711651
4,M1(7),M1,M,Jul,M_Jul,1.2,9.3,3.3,1.926,0.014,...,19.058211,13.416882,15.926868,16.323585,13.957118,17.296312,15.262719,15.544962,14.122522,19.103356

In [ ]:
dfMD_log_input=dfMD_log.iloc[:,13:].to_numpy()
dfMD_log_target=dfMD_log['class2'].to_numpy()

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(dfMD_log_input, dfMD_log_target, random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)
print("Train Accuracy:", lr.score(train_input, train_target))
print("Test Accuracy:", lr.score(test_input, test_target))

1.0
0.8703703703703703

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# 4. MinMax transformation
scaler = MinMaxScaler()
dfMD_log[dfMD_log.columns[13:]] = scaler.fit_transform(dfMD_log[dfMD_log.columns[13:]])

# Save the transformed data to a new .csv file
dfMD_log.to_csv("dfMD_log_MM.csv", index=False)

dfMD_log_MM = pd.read_csv("dfMD_log_MM.csv")
dfMD_log_MM.head()

,Name,class1,class2,class3,class4,BOD,DO,COD,T-N,T-P,...,C10 H10 N4 O2 S,C10 H10 N4 O3 S,C10 H10 O(1/2),C10 H10 O(2/2),C10 H10 O2(1/2),C10 H10 O2(2/2),C10 H10 O3(1/3),C10 H10 O3(2/3),C10 H10 O3(3/3),C10 H10 O3 Se
0,M1(3),M1,M,Mar,M_Mar,1.0,12.8,2.8,2.278,0.013,...,0.089958,0.114010,0.968144,0.300463,0.479000,0.235901,0.250747,0.760415,0.554876,0.549708
1,M1(4),M1,M,Apr,M_Apr,1.2,11.3,3.2,2.342,0.006,...,0.245094,0.326787,0.788296,0.512505,0.586363,0.531332,0.633155,0.029858,0.249115,0.631090
2,M1(5),M1,M,May,M_May,1.2,10.7,3.2,1.326,0.004,...,0.126230,0.945268,0.542685,0.620120,0.813522,0.723313,0.949362,0.450614,0.974742,0.258689
3,M1(6),M1,M,Jun,M_Jun,1.2,9.7,3.1,1.670,0.008,...,0.138159,0.297426,0.571827,1.000000,1.000000,0.877944,0.403982,1.000000,0.724904,0.514236
4,M1(7),M1,M,Jul,M_Jul,1.2,9.3,3.3,1.926,0.014,...,0.766732,0.386816,0.255416,0.268895,0.368536,0.232133,0.461484,0.493956,0.357054,0.894870

In [ ]:
dfMD_log_MM_input=dfMD_log_MM.iloc[:,13:].to_numpy()
dfMD_log_MM_target=dfMD_log_MM['class2'].to_numpy()

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(dfMD_log_MM_input, dfMD_log_MM_target, random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)
print("Train Accuracy:", lr.score(train_input, train_target))
print("Test Accuracy:", lr.score(test_input, test_target))

1.0
0.8518518518518519

In [ ]:
from sklearn.preprocessing import StandardScaler

# 4. Standard transformation
scaler = StandardScaler()
dfMD_log[dfMD_log.columns[13:]] = scaler.fit_transform(dfMD_log[dfMD_log.columns[13:]])

# Save the transformed data to a new .csv file
dfMD_log.to_csv("dfMD_log_ST.csv", index=False)

dfMD_log_ST = pd.read_csv("dfMD_log_ST.csv")
dfMD_log_ST.head()

,Name,class1,class2,class3,class4,BOD,DO,COD,T-N,T-P,...,C10 H10 N4 O2 S,C10 H10 N4 O3 S,C10 H10 O(1/2),C10 H10 O(2/2),C10 H10 O2(1/2),C10 H10 O2(2/2),C10 H10 O3(1/3),C10 H10 O3(2/3),C10 H10 O3(3/3),C10 H10 O3 Se
0,M1(3),M1,M,Mar,M_Mar,1.0,12.8,2.8,2.278,0.013,...,-1.434222,-1.042317,2.023264,0.063280,-0.164794,-0.558915,-0.557065,1.740966,0.456661,0.469279
1,M1(4),M1,M,Apr,M_Apr,1.2,11.3,3.2,2.342,0.006,...,-0.822334,-0.048160,1.440972,1.127316,0.488720,0.512349,0.889651,-1.329257,-0.848186,0.724766
2,M1(5),M1,M,May,M_May,1.2,10.7,3.2,1.326,0.004,...,-1.291156,2.841572,0.645760,1.667336,1.871436,1.208497,2.085918,0.439002,2.248461,-0.444328
3,M1(6),M1,M,Jun,M_Jun,1.2,9.7,3.1,1.670,0.008,...,-1.244106,-0.185342,0.740111,3.573593,3.006522,1.769205,0.022648,2.747844,1.182265,0.357922
4,M1(7),M1,M,Jul,M_Jul,1.2,9.3,3.3,1.926,0.014,...,1.235111,0.232317,-0.284326,-0.095132,-0.837187,-0.572581,0.240190,0.621153,-0.387552,1.552861

In [ ]:
dfMD_log_ST_input=dfMD_log_ST.iloc[:,13:].to_numpy()
dfMD_log_ST_target=dfMD_log_ST['class2'].to_numpy()

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(dfMD_log_ST_input, dfMD_log_ST_target, random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)
print("Train Accuracy:", lr.score(train_input, train_target))
print("Test Accuracy:", lr.score(test_input, test_target))

1.0
0.8703703703703703

In [ ]:
from sklearn.preprocessing import RobustScaler

# 4. Robust transformation
scaler = RobustScaler()
dfMD_log[dfMD_log.columns[13:]] = scaler.fit_transform(dfMD_log[dfMD_log.columns[13:]])

# Save the transformed data to a new .csv file
dfMD_log.to_csv("dfMD_log_RB.csv", index=False)

dfMD_log_RB = pd.read_csv("dfMD_log_RB.csv")
dfMD_log_RB.head()

,Name,class1,class2,class3,class4,BOD,DO,COD,T-N,T-P,...,C10 H10 N4 O2 S,C10 H10 N4 O3 S,C10 H10 O(1/2),C10 H10 O(2/2),C10 H10 O2(1/2),C10 H10 O2(2/2),C10 H10 O3(1/3),C10 H10 O3(2/3),C10 H10 O3(3/3),C10 H10 O3 Se
0,M1(3),M1,M,Mar,M_Mar,1.0,12.8,2.8,2.278,0.013,...,-0.729199,-0.622167,1.311430,-0.043627,0.057953,-0.329213,-0.379000,1.361734,0.442958,0.236474
1,M1(4),M1,M,Apr,M_Apr,1.2,11.3,3.2,2.342,0.006,...,-0.398403,0.083065,0.971990,0.591663,0.957013,0.339760,0.543220,-0.424913,-0.537333,0.366846
2,M1(5),M1,M,May,M_May,1.2,10.7,3.2,1.326,0.004,...,-0.651855,2.132976,0.508430,0.914086,2.859261,0.774483,1.305789,0.604085,1.789083,-0.229728
3,M1(6),M1,M,Jun,M_Jun,1.2,9.7,3.1,1.670,0.008,...,-0.626419,-0.014249,0.563431,2.052231,4.420836,1.124629,-0.009458,1.947663,0.988083,0.179650
4,M1(7),M1,M,Jul,M_Jul,1.2,9.3,3.3,1.926,0.014,...,0.713884,0.282029,-0.033753,-0.138208,-0.867081,-0.337747,0.129216,0.710084,-0.191273,0.789412

In [ ]:
dfMD_log_RB_input=dfMD_log_RB.iloc[:,13:].to_numpy()
dfMD_log_RB_target=dfMD_log_RB['class2'].to_numpy()

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(dfMD_RB_input, dfMD_RB_target, random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)
print("Train Accuracy:", lr.score(train_input, train_target))
print("Test Accuracy:", lr.score(test_input, test_target))

1.0
0.7592592592592593

In [ ]:
# Subtract the mean of each column and divide by the square of the standard deviation of each column
dfMD_log.iloc[:, 13:] = (dfMD_log.iloc[:, 13:] - dfMD_log.iloc[:, 13:].mean()) / dfMD_log.iloc[:, 13:].std()**0.5

# Move the first column (sample name) and second column (group name) to the front and combine the data
cols = dfMD_log.columns.tolist()
cols = cols[:13] + cols[13:]
dfMD_log = dfMD_log[cols]
dfMD.to_csv("dfMD_log_PR.csv", index=False)
dfMD_log_PR = pd.read_csv("dfMD_log_PR.csv")
dfMD_log_PR.head()

,Name,class1,class2,class3,class4,BOD,DO,COD,T-N,T-P,...,C10 H10 N4 O2 S,C10 H10 N4 O3 S,C10 H10 O(1/2),C10 H10 O(2/2),C10 H10 O2(1/2),C10 H10 O2(2/2),C10 H10 O3(1/3),C10 H10 O3(2/3),C10 H10 O3(3/3),C10 H10 O3 Se
0,M1(3),M1,M,Mar,M_Mar,1.0,12.8,2.8,2.278,0.013,...,15.554147,12.572277,19.363463,16.496040,14.449083,17.307655,14.497019,16.717851,15.089256,16.934536
1,M1(4),M1,M,Apr,M_Apr,1.2,11.3,3.2,2.342,0.006,...,16.357379,13.231031,18.496282,17.654408,14.927235,18.196862,15.886475,13.502110,13.595036,17.445900
2,M1(5),M1,M,May,M_May,1.2,10.7,3.2,1.326,0.004,...,15.741951,15.145842,17.312006,18.242303,15.938918,18.774702,17.035393,15.354179,17.141100,15.105926
3,M1(6),M1,M,Jun,M_Jun,1.2,9.7,3.1,1.670,0.008,...,15.803714,13.140131,17.452519,20.317558,16.769418,19.240120,15.053787,17.772451,15.920167,16.711651
4,M1(7),M1,M,Jul,M_Jul,1.2,9.3,3.3,1.926,0.014,...,19.058211,13.416882,15.926868,16.323585,13.957118,17.296312,15.262719,15.544962,14.122522,19.103356

In [ ]:
dfMD_log_PR_input=dfMD_log_PR.iloc[:,13:].to_numpy()
dfMD_log_PR_target=dfMD_log_PR['class2'].to_numpy()

from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target=train_test_split(dfMD_PR_input, dfMD_PR_target, random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20, max_iter=1000)
lr.fit(train_input, train_target)
print("Train Accuracy:", lr.score(train_input, train_target))
print("Test Accuracy:", lr.score(test_input, test_target))

1.0
0.7777777777777778